import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import { fileURLToPath, URL } from 'node:url'

// Vite config for the Nexus AI client.
// The dev server proxies /api calls to the Express backend so we avoid
// CORS issues during local development. The `@shared` alias lets the client
// import the shared model registry that also powers the server.
const sharedDir = fileURLToPath(new URL('../shared', import.meta.url))

export default defineConfig({
  plugins: [
    react(),
    // Installable app (Android/desktop "Install", iOS "Add to Home Screen").
    // The service worker precaches the shell so it opens instantly and works
    // offline for cached pages; /api is never cached — every request goes to
    // the backend. Icons are generated by scripts/gen-icons.mjs.
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.svg', 'apple-touch-icon.png', 'og-image.svg'],
      manifest: {
        name: 'Nexus AI — Multi-Model AI Hub',
        short_name: 'Nexus AI',
        description: 'A multi-model AI hub for chat, pipelines, video vision, and creative tools.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        orientation: 'portrait-primary',
        background_color: '#0b0f17',
        theme_color: '#0b0f17',
        categories: ['productivity', 'utilities'],
        icons: [
          { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
          { src: '/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        // The app bundle (~1.8MB) and the PDF worker (~1.2MB) are both over
        // workbox's 2MB default.
        maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,
        navigateFallback: '/index.html',
        navigateFallbackDenylist: [/^\/api\//],
        globPatterns: ['**/*.{js,css,html,svg,png,woff2}'],
      },
    }),
  ],
  resolve: {
    alias: {
      '@shared': sharedDir,
    },
  },
  server: {
    port: 5173,
    // Allow serving files from the monorepo's shared folder (outside client root).
    fs: { allow: ['..'] },
    proxy: {
      '/api': {
        target: 'http://localhost:4000',
        changeOrigin: true,
      },
    },
  },
})
